CREATE DATABASE `airline` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `airline`;

CREATE TABLE `passenger` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(20) DEFAULT NULL,
  `AGE` int(11) DEFAULT NULL,
  `GENDER` varchar(10) DEFAULT NULL,
  `PHONE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PHONE_UNIQUE` (`PHONE`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8 COMMENT='Table to store passanger details';


CREATE TABLE `reservation` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRICE` int(11) DEFAULT NULL,
  `PASSENGER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `RESERVATION_PASSENGER_ID_FK_idx` (`PASSENGER_ID`),
  CONSTRAINT `RESERVATION_PASSENGER_ID_FK` FOREIGN KEY (`PASSENGER_ID`) REFERENCES `passenger` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT='Table to store reservation details';

CREATE TABLE `flight` (
  `ID` varchar(20) NOT NULL,
  `PRICE` int(11) DEFAULT NULL,
  `LOC_FROM` varchar(45) DEFAULT NULL,
  `LOC_TO` varchar(45) DEFAULT NULL,
  `DEPARTURE` datetime DEFAULT NULL,
  `ARRIVAL` datetime DEFAULT NULL,
  `SEATS_LEFT` int(11) DEFAULT NULL,
  `DESCR` varchar(45) DEFAULT NULL,
  `PLANE_MODEL` varchar(45) DEFAULT NULL,
  `PLANE_MANUFACTURER` varchar(45) DEFAULT NULL,
  `PLANE_YEAR_OF_MANUFACTURE` int(11) DEFAULT NULL,
  `PLANE_CAPACITY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Table to store flight details';


CREATE TABLE `flight_passenger` (
  `FLIGHT_ID` varchar(20) NOT NULL,
  `PASSENGER_ID` int(11) NOT NULL,
  PRIMARY KEY (`FLIGHT_ID`,`PASSENGER_ID`),
  KEY `FLT_PASS_FLT_ID_idx` (`FLIGHT_ID`),
  KEY `FLT_PASS_PASS_ID_FK_idx` (`PASSENGER_ID`),
  CONSTRAINT `FLT_PASS_FLT_ID_FK` FOREIGN KEY (`FLIGHT_ID`) REFERENCES `flight` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FLT_PASS_PASS_ID_FK` FOREIGN KEY (`PASSENGER_ID`) REFERENCES `passenger` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Join table for flights and passanger';


CREATE TABLE `reservation_flight` (
  `RESERVATION_ID` int(11) NOT NULL,
  `FLIGHT_ID` varchar(45) NOT NULL,
  PRIMARY KEY (`RESERVATION_ID`,`FLIGHT_ID`),
  KEY `RES_FLT_FLT_ID_FK_idx` (`FLIGHT_ID`),
  CONSTRAINT `RES_FLT_FLT_ID_FK` FOREIGN KEY (`FLIGHT_ID`) REFERENCES `flight` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `RES_FLT_RES_ID_FK` FOREIGN KEY (`RESERVATION_ID`) REFERENCES `reservation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Join table for reservations and flights';